Repository wuhan-support/backend, pull requests merged in 2020-02, with the labels that each got.

#12 Add feature for community supplies.
  main.go
  types.go
Labels: approved, lgtm, size/L

#13 Fixed parsing bug, if only use the `Name` field of SubmissionSupply.
  types.go
Labels: approved, lgtm, size/XS

#14 Init K8S automatically deploy
  .github/workflows/dockerpush.yml
  manifests/be-deployment.yaml
  manifests/be-service.yaml
Labels: approved, enhancement, lgtm, size/L

#16 Release
  .github/workflows/dockerpush.yml
  main.go
  manifests/be-deployment.yaml
  manifests/be-service.yaml
  types.go
Labels: approved, size/L

#17 Fix go modules missing
  Dockerfile
Labels: approved, lgtm, size/XS

#18 Fix go module miss
  Dockerfile
  go.mod
  go.sum
  main.go
Labels: approved, size/M

#19 multiwriter support
  main.go
Labels: approved, size/XS

#20 logger
  main.go
Labels: approved, size/XS

#21 Solved 500
  go.mod
  main.go
  service_test.go
Labels: approved, size/M
